version: '3.9'

services:
  impostor-db:
    image: postgres:17
    container_name: impostor-postgres-db
    restart: unless-stopped
    ports:
      - "16545:5432"
    environment:
      POSTGRES_DB: impostor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - impostor-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  impostor-backend:
    image: ghcr.io/maelseewald/impostor-backend:latest
    container_name: impostor-backend
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-9769}:${SERVER_PORT:-9769}"
      - "${SOCKET_PORT:-6861}:${SOCKET_PORT:-6861}"
    environment:
      DB_URL: jdbc:postgresql://impostor-db:5432/impostor?currentSchema=impostor
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: impostor
      DB_OWNER_USERNAME: postgres
      DB_OWNER_PASSWORD: postgres
      DB_APPL_ROLE: rl_impostor_app
      SERVER_PORT: ${SERVER_PORT:-9769}
      SOCKET_HOST: impostor-backend
      SOCKET_PORT: ${SOCKET_PORT:-6861}
    depends_on:
      impostor-db:
        condition: service_healthy

  impostor-frontend:
    image: ghcr.io/maelseewald/impostor-frontend:latest
    container_name: impostor-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - impostor-backend

volumes:
  impostor-db-data:
