buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.flywaydb:flyway-database-postgresql:11.10.4'
    }
}

plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.flywaydb.flyway' version '11.10.4'
    id 'org.openapi.generator' version '7.0.1'
}

group = 'com.impostor'
version = System.env.VERSION ?: '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'io.swagger.core.v3:swagger-annotations:2.2.15'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
    implementation 'org.openapitools:jackson-databind-nullable:0.2.6'
    implementation 'io.swagger.core.v3:swagger-models:2.2.15'
    implementation 'org.mapstruct:mapstruct:1.5.0.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.0.Final'
    implementation 'com.corundumstudio.socketio:netty-socketio:2.0.13'
}

ext {
    databaseName = System.env.DB_NAME ?: 'impostor'
    databaseUsername = System.env.DB_USERNAME ?: 'postgres'
    databasePassword = System.env.DB_PASSWORD ?: 'postgres'
    databaseOwnerUsername = System.env.DB_OWNER_USERNAME ?: 'postgres'
    databaseOwnerPassword = System.env.DB_OWNER_PASSWORD ?: 'postgres'
    databaseUrl = System.env.DB_URL ?: "jdbc:postgresql://localhost:16545/${databaseName}"
    databaseApplRole = System.env.DB_APPL_ROLE ?: 'rl_impostor_app'
}

flyway {
    url = "${databaseUrl}"
    user = "${databaseUsername}"
    password = "${databasePassword}"
    locations = ['/db/setup']
    schemas = ['impostor']
    cleanDisabled = true
    placeholders = ['db.name': "${databaseName}", 'db.role.application': "${databaseApplRole}"]
}

flywayInfo.dependsOn classes
flywayMigrate.dependsOn classes

openApiGenerate {
    generatorName = 'spring'
    inputSpec = "$projectDir/openapi.yaml".toString()
    outputDir = "$projectDir/generated".toString()
    apiPackage = 'com.impostor.impostor.generated.api'
    modelPackage = 'com.impostor.impostor.generated.model'
    invokerPackage = 'com.impostor.impostor.generated.invoker'
    skipOverwrite = false
    configOptions.set([
            dateLibrary: "java8",
            useJakartaEe: "true",
            interfaceOnly: "true",
            useBeanValidation: "true"
    ])
}

sourceSets {
    main {
        java {
            srcDirs += 'generated/src/main/java'
        }
    }
}

tasks.named('compileJava') {
    dependsOn tasks.named('openApiGenerate')
}

tasks.named('test') {
    useJUnitPlatform()
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}

wrapper {
    gradleVersion = '9.1.0'
    distributionUrl = "https://services.gradle.org/distributions/gradle-${gradleVersion}-all.zip"
}
