INSERT INTO main_words (word) VALUES
('Netflix'), ('Inlandsflug'), ('Badreiniger'), ('Amazonas'), ('Topf'),
('Spülmaschine'), ('Zahnbürste'), ('Fotoalbum'), ('Autobiografie'), ('Heftklammer'),
('Kopfhörer'), ('Kaffeetasse'), ('Buch'), ('T-Shirt'), ('Schreibtisch'), ('Kühlschrank'),
('Handy'), ('Fernseher'), ('Laptop'), ('Tablet'), ('Mauspad'),
('Bleistift'), ('Notizbuch'), ('Schlüsselbund'), ('Geldbörse'), ('Uhr'),
('Brille'), ('Schuhe'), ('Jacke'), ('Hut'), ('Sonnenbrille'),
('Kamera'), ('Mikrofon'), ('Lautsprecher'), ('Regisseur'), ('Handtasche'),
('Unterwasserkamera'), ('Skigebiet'), ('Musik'), ('Streamingdienst'), ('Strand'),
('Hund'), ('Zahnseide'), ('Kopfkissen'), ('Decke'), ('Bettwäsche'),
('Handtuch'), ('Seife'), ('Duschgel'), ('Shampoo'), ('Zahnpasta'),
('Rasierapparat'), ('Kamm'), ('Bürste'), ('Parfüm'), ('Make-up'),
('Lippenstift'), ('Nagellack'), ('Haargel'), ('Haarspray'), ('Sonnencreme'),
('Aftershave'), ('Lichtshow'), ('Kerze'), ('Feuerzeug'), ('Streichhölzer'),
('Taschenlampe'), ('Batterie'), ('Steckdose'), ('Verlängerungskabel'), ('Ladegerät'),
('Powerbank'), ('USB-Kabel'), ('Pfanne'), ('Staubsaugerroboter'), ('Kartoffelkanone'),
('Marshmallow'), ('Gummihuhn'), ('Klobrille'), ('Puddingbecher'), ('Tintenfisch'),
('Luftmatratze'), ('Konfettikanone'), ('Wackelpudding'), ('Sockenpuppe'), ('Bananenbrot'),
('Quasselstrippe'), ('Wurstmaschine'), ('Schneekugel'), ('Sandburg'), ('Toilettenpapier'),
('Klobürste'), ('Quietscheente'), ('Luftballon'), ('Pizzaofen'), ('Kaktus'),
('Einhorntasse'), ('Keksdose'), ('Spaghettizange'), ('Rollschuhe'), ('Plastikbanane'),
('Schneemann'), ('Schuhanzieher'), ('Besenstiel'), ('Wasserkocher'), ('Eierschneider'),
('Donut'), ('Wackeldackel'), ('Lachsbrötchen'), ('Büroklammer'), ('Schneebesen'),
('Glitzerschuh'), ('Campingstuhl'), ('Giesskanne'), ('Milchaufschäumer'), ('Seifenblasen'),
('Trillerpfeife'), ('Kartoffelschäler'), ('Fliegenklatsche')
ON CONFLICT DO NOTHING;
