spring:
  application:
    name: "impostor"
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
  flyway:
    url: "${spring.datasource.url}"
    user: "${spring.datasource.username}"
    password: "${spring.datasource.password}"
    locations: "classpath:db/setup,classpath:db/migration"
    ignore-migration-patterns: "*:missing,*:future"
    out-of-order: true
logging:
  level:
    root: "info"
server:
  port: ${SERVER_PORT}
socket:
  host: ${SOCKET_HOST}
  port: ${SOCKET_PORT}
